import Vector2 from "./Vector2D";
type Matrix2D = [[number, number], [number, number]];
export default Matrix2D;
export declare const matrix2D: (a: number, b: number, c: number, d: number) => Matrix2D;
export declare const id2: () => Matrix2D;
export declare const det: ([[a, b], [c, d]]: Matrix2D) => number;
export declare const addMM: (...matrices: Matrix2D[]) => Matrix2D;
export declare const multMM: ([[a00, a01], [a10, a11]]: Matrix2D, [[b00, b01], [b10, b11]]: Matrix2D) => Matrix2D;
export declare const multMV: ([[a00, a01], [a10, a11]]: Matrix2D, [b0, b1]: Vector2) => Vector2;
export declare const multSM: (scale: number, [[a00, a01], [a10, a11]]: Matrix2D) => Matrix2D;
export declare const inverse: (a: Matrix2D) => Matrix2D;
export declare const solve: (m: Matrix2D, b: Vector2) => Vector2;
