"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Geometry3D = exports.Geometry2D = exports.Coord = void 0;
const Coord_1 = require("./Coord");
const Geometry2D_1 = require("./Geometry2D");
Object.defineProperty(exports, "Geometry2D", { enumerable: true, get: function () { return Geometry2D_1.Geometry2D; } });
const Geometry3D_1 = require("./Geometry3D");
Object.defineProperty(exports, "Geometry3D", { enumerable: true, get: function () { return Geometry3D_1.Geometry3D; } });
const Coord = { x: Coord_1.x, y: Coord_1.y, z: Coord_1.z };
exports.Coord = Coord;
